Factory.define('orderForAF', Orders,
  Factory.extend('order', {
    shipping: [{address: faker.reaction.address()}],
    billing: [{address: faker.reaction.address()}]
  })
);

Factory.define('afProduct', ReactionCore.Collections.Products,
  Factory.extend('product', {
    _id: 'vaYYEW7b8yqBcNCHy',
    variants:
     [ { _id: 'wqDDe5e2z7xSW9bzT',
         type: 'variant',
         title: 'Grayeen',
         optionTitle: 'color',
         price: 1,
         pricePerDay: 1,
         inventoryQuantity: 22,
         taxable: true,
         weight: 1,
         inventoryManagement: true,
         inventoryPolicy: true },
       { _id: 'AHL7cCScQ5u4z2wqy',
         parentId: 'wqDDe5e2z7xSW9bzT',
         type: 'variant',
         sku: 'MB005',
         manufacturerSku: 'MB005',
         location: 'A3',
         color: 'Grayeen',
         size: 'Small',
         title: 'size',
         optionTitle: 'Small',
         inventoryQuantity: 3,
         compareAtPrice: 1,
         price: 1,
         pricePerDay: 1,
         taxable: true,
         weight: 1,
         inventoryManagement: true,
         inventoryPolicy: true },
       { _id: '2uj3CNsrLuutHXMQv',
         parentId: 'wqDDe5e2z7xSW9bzT',
         type: 'variant',
         sku: 'MB006',
         manufacturerSku: 'MB006',
         location: 'A3',
         color: 'Grayeen',
         size: 'Medium',
         title: 'size',
         optionTitle: 'Medium',
         inventoryQuantity: 5,
         compareAtPrice: 1,
         price: 1,
         pricePerDay: 1,
         taxable: true,
         weight: 1,
         inventoryManagement: true,
         inventoryPolicy: true },
       { _id: 'GJb6QCRRW4ngCfBby',
         parentId: 'wqDDe5e2z7xSW9bzT',
         type: 'variant',
         sku: 'MB007',
         manufacturerSku: 'MB007',
         location: 'A3',
         color: 'Grayeen',
         size: 'Large',
         title: 'size',
         optionTitle: 'Large',
         inventoryQuantity: 7,
         compareAtPrice: 1,
         price: 1,
         pricePerDay: 1,
         taxable: true,
         weight: 1,
         inventoryManagement: true,
         inventoryPolicy: true },
       { _id: 'e5Ma52fGtMgC88WaN',
         parentId: 'wqDDe5e2z7xSW9bzT',
         type: 'variant',
         sku: 'MB008',
         manufacturerSku: 'MB008',
         location: 'A3',
         color: 'Grayeen',
         size: 'Extra Large',
         title: 'size',
         optionTitle: 'Extra Large',
         inventoryQuantity: 5,
         compareAtPrice: 1,
         price: 1,
         pricePerDay: 1,
         taxable: true,
         weight: 1,
         inventoryManagement: true,
         inventoryPolicy: true },
       { _id: 'at7ipuLavKLs26v4R',
         parentId: 'wqDDe5e2z7xSW9bzT',
         type: 'variant',
         sku: 'MB009',
         manufacturerSku: 'MB009',
         location: 'A3',
         color: 'Grayeen',
         size: 'XXL',
         title: 'size',
         optionTitle: 'XXL',
         inventoryQuantity: 2,
         compareAtPrice: 1,
         price: 1,
         pricePerDay: 1,
         taxable: true,
         weight: 1,
         inventoryManagement: true,
         inventoryPolicy: true },
       { _id: 'Az9HQgJp5fbjm5zf3',
         type: 'variant',
         title: 'True Black',
         optionTitle: 'color',
         price: 1,
         pricePerDay: 1,
         inventoryQuantity: 24,
         taxable: true,
         weight: 1,
         inventoryManagement: true,
         inventoryPolicy: true },
       { _id: 'jzHd2W5anAZiSQE7a',
         parentId: 'Az9HQgJp5fbjm5zf3',
         type: 'variant',
         sku: 'MB010',
         manufacturerSku: 'MB010',
         location: 'A3',
         color: 'True Black',
         size: 'Small',
         title: 'size',
         optionTitle: 'Small',
         inventoryQuantity: 4,
         compareAtPrice: 1,
         price: 1,
         pricePerDay: 1,
         taxable: true,
         weight: 1,
         inventoryManagement: true,
         inventoryPolicy: true },
       { _id: 'nJ89rZ2fYxmXuQxgN',
         parentId: 'Az9HQgJp5fbjm5zf3',
         type: 'variant',
         sku: 'MB011',
         manufacturerSku: 'MB011',
         location: 'A3',
         color: 'True Black',
         size: 'Medium',
         title: 'size',
         optionTitle: 'Medium',
         inventoryQuantity: 8,
         compareAtPrice: 1,
         price: 1,
         pricePerDay: 1,
         taxable: true,
         weight: 1,
         inventoryManagement: true,
         inventoryPolicy: true },
       { _id: 'KbkizMfaNyXpp8Zow',
         parentId: 'Az9HQgJp5fbjm5zf3',
         type: 'variant',
         sku: 'MB012',
         manufacturerSku: 'MB012',
         location: 'A3',
         color: 'True Black',
         size: 'Large',
         title: 'size',
         optionTitle: 'Large',
         inventoryQuantity: 10,
         compareAtPrice: 1,
         price: 1,
         pricePerDay: 1,
         taxable: true,
         weight: 1,
         inventoryManagement: true,
         inventoryPolicy: true },
       { _id: 'McdnJfmwDcfa262yA',
         parentId: 'Az9HQgJp5fbjm5zf3',
         type: 'variant',
         sku: 'MB013',
         manufacturerSku: 'MB013',
         location: 'A3',
         color: 'True Black',
         size: 'XXL',
         title: 'size',
         optionTitle: 'XXL',
         inventoryQuantity: 2,
         compareAtPrice: 1,
         price: 1,
         pricePerDay: 1,
         taxable: true,
         weight: 1,
         inventoryManagement: true,
         inventoryPolicy: true } ],
    colors: [ 'Grayeen', 'True Black' ],
    shopId: 'Jw2KczCDcL7j2msKr',
    vendor: 'Burton',
    gender: 'Mens',
    title: 'Cargo Pant',
    pageTitle: 'Cargo Pant',
    productType: 'Pants',
    description: 'Cargo Pant',
    handle: 'mens-cargo-pant',
    isVisible: false,
    type: 'rental',
    requiresShipping: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    workflow: {
      status: 'new'
    },
    cleaningBuffer: 0
  })
);

